food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:item_id>/',views.detail, name='detail'),
    path('add/',views.create_item, name='create_item'),
    path('edit/<int:item_id>/',views.edit_item, name='edit_item'),
    
    path('delete/<int:item_id>/',views.delete_item, name='delet_item'),

]

foodapp/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('register/',user_views.register, name="register"),
    path('login/',authentication_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='accounts/logout.html'),name='logout'),
    path('profile/',user_views.profilepage, name="profile"),
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    image = models.ImageField(default='profile/pictures/profilepic.jpg',upload_to='profile/pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    id = models.AutoField(primary_key=True)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://static.vecteezy.com/system/resources/previews/003/170/825/original/isolated-food-plate-fork-and-spoon-design-free-vector.jpg" )

    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item  # Fix the typo here
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RegistrationForm


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account is created, Please login')
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request, 'accounts/register.html', {'form': form})

@login_required
def profilepage(request):
    return render(request,'accounts/profile.html' )

food/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
#models loaader
from .models import Item
from .forms import ItemForm

# Create your views here.
@login_required
def index(request):
    item_list = Item.objects.all()
    

    context={
            'item_list': item_list ,
    }

    return render(request, 'food/index.html', context)


@login_required
def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context={
            'item': item ,
    }
    return render(request, 'food/detail.html', context)
@login_required
def create_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('food:index')  # Redirect to the desired URL after successful form submission
    else:
        form = ItemForm()

    context = {'form': form}
    return render(request, 'food/item-form.html', context)
@login_required
def edit_item(request, item_id):
    item = get_object_or_404(Item, pk=item_id)

    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('food:index')  # Redirect to the desired URL after successful form submission
    else:
        form = ItemForm(instance=item)

    context = {'form': form, 'item': item}
    return render(request, 'food/item-form.html', context)
@login_required
def delete_item(request, item_id):
    if request.method == 'POST':
        item = get_object_or_404(Item, pk=item_id)
        
        if item:
            item.delete()
            return redirect('food:index')
        else:
            return HttpResponse(status=404)
    else:
        return render(request, 'food/delete-item.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" >Login</button>
</form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<h1>You have been logout !</h1>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block body %}
    <h1>
        {{ user.username }}
        
    </h1>
    <img src="{{user.profile.image.url}}" alt="{{user.profile.image.url}}" height="120px">
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block body %}
  <h2>Register</h2>
  <form method="post" action="{% url 'register' %}">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Register</button>
  </form>
{% endblock %}

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body class="container-fluid">
   
    <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand ms-3" href="#">Navbar</a>
           
            <div class="navbar" >
                <a href="{% url 'food:create_item' %}" class="nav-item nav-link link-primary me-3">Add Item</a>
                <a href="#" class="nav-item nav-link link-primary me-3">Delete Item</a>
                <a href="#" class="nav-item nav-link link-primary me-3">View Item</a>
            </div>
    </nav>
    <div class="content" style="margin-top: 20px;">
        {% block body %}

        {% endblock %}
    </div>
    
    
</body>
</html>

food/templates/food/delete-item.html
<form action="" method="POST">
    {% csrf_token %}
    <h2>
        Are you going to delete {{item.item_name}}
    </h2>
    <button type="submit"> Confirm </button>
</form>

food/templates/food/detail.html
{% extends 'base.html' %}
{% block body %}
    <div class="row">
        <div class="offset-md-2 col-4">
            <img src="{{item.item_image}}" alt="{{item.item_name}}" class="card"height="300px" width="300px;">
        </div>
        <div class="col-6">
            <h3>{{item.item_name}}</h3>
            <h3>{{item.item_desc}}</h3>
            <h3>{{item.item_price}}</h3>
            <a href="{% url 'food:edit_item' item.id %}" class="btn btn-primary">Edit</a>
            <a href="{% url 'food:delet_item' item.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
    
{% endblock %}

food/templates/food/index.html
{% extends 'base.html' %}
{% block body %}
    {% for item in item_list %}
        
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img src="{{item.item_image}}" alt="card" height="150px" width="150px;">
        </div>
        <div class="col-md-4">
            <h2>{{item.item_name}}</h3>
            <h3>{{item.item_desc}}</h3>
            <h3>{{item.item_price}}</h3>
            <h3>{{item.user_name}}</h3>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %} " class="btn btn-success">Details </a>
        </div>

    </div>
    {% endfor %}
{% endblock %}

food/templates/food/item-form.html
{% extends 'base.html' %}
{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body class="container-fluid">
   
    <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand ms-3" href="#">Navbar</a>
           
            <div class="navbar" >
                <a href="{% url 'food:index' %}" class="nav-item nav-link link-primary me-3">List Item</a>
                <a href="{% url 'food:create_item' %}" class="nav-item nav-link link-primary me-3">Add Item</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'profile' %}" class="nav-item nav-link link-primary me-3">Profile</a>
                    <a href="{% url 'logout' %}" class="nav-item nav-link link-primary me-3">Logout</a>
                {% else %}
                    <a href="{% url 'login' %}" class="nav-item nav-link link-primary me-3">Login</a>
                {% endif %}
            </div>
    </nav>
    <div class="content" style="margin-top: 20px;">
        {% if messages %}
            {% for message in messages  %}
                <div class="alert alert-{{ message.tags }}">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
        {% block body %}

        {% endblock %}
    </div>
    
    
</body>
</html>